/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokobuku;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author WINDOWS 10
 */
public class Penjualan extends javax.swing.JInternalFrame {

    private static Connection koneksi;
    private DefaultTableModel model;
    private DefaultTableModel model1;
    private PreparedStatement pst;
    
    public Penjualan() {
        initComponents();
        model = new DefaultTableModel();
        this.tabel_data.setModel(model);
        model1 = new DefaultTableModel();
        this.jTable2.setModel(model1);
        model.addColumn("ID_Buku");
        model.addColumn("Nama_Barang");
        model.addColumn("Jumlah");
        model.addColumn("Harga");
        model1.addColumn("ID_Buku");
        model1.addColumn("Nama_Barang");
        model1.addColumn("Jumlah");
        model1.addColumn("Harga");
        ambil_data_tabel();
        ambil_data_tabel1();
        getSum();
    }
private static Connection buka_koneksi() {
        if (koneksi == null) {
            try {
                String url = "jdbc:mysql://localhost:3306/toko";
                String user = "root";
                String password = "";
                DriverManager.registerDriver(new com.mysql.jdbc.Driver());
                koneksi = DriverManager.getConnection(url, user, password);
            } catch (SQLException t) {
                System.out.println("Error membuat koneksi");
            }
        }
        return koneksi;
    }

    private void ambil_data_tabel() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = buka_koneksi();
            Statement s = c.createStatement();
            String sql = "Select * from buku";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                Object[] o = new Object[4];
                o[0] = r.getString("id_buku");
                o[1] = r.getString("judul");
                o[2] = r.getString("stok");
                o[3] = r.getString("harga");
                model.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi kesalahan " + e.getMessage());
        }
    }
    private void ambil_data_tabel1() {
        model1.getDataVector().removeAllElements();
        model1.fireTableDataChanged();
        try {
            Connection c = buka_koneksi();
            Statement s = c.createStatement();
            String sql = "Select * from penjualan1";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                Object[] o = new Object[4];
                o[0] = r.getString("id_barang");
                o[1] = r.getString("nama_barang");
                o[2] = r.getString("jumlah");
                o[3] = r.getString("harga");
                model1.addRow(o);
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi kesalahan " + e.getMessage());
        }
    }
     public void getSum()
    {
        int sum = 0;
        for(int i = 0; i < jTable2.getRowCount(); i++)
        {
            sum = sum + Integer.parseInt(jTable2.getValueAt(i, 3).toString());
        } 
        txttotal.setText(Integer.toString(sum));
    }
     private void filter(String query) {
        TableRowSorter<DefaultTableModel> ft = new TableRowSorter<DefaultTableModel>(model);
        tabel_data.setRowSorter(ft);
        ft.setRowFilter(RowFilter.regexFilter(query));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        btntransaksi = new javax.swing.JButton();
        txttanggal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btntotal = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttotal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtkembalian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btntambah = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        btnhapus = new javax.swing.JButton();
        txtjumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Transaksi Penjualan");

        jLabel9.setText("Cari Nama/ID");

        btntransaksi.setText("Transaksi Baru");
        btntransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransaksiActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang", "Jumlah", "Harga"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        jLabel4.setText("Total");

        txttotal.setText("0");

        jLabel6.setText("Bayar");

        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Barang", "Nama_Barang", "Jumlah", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabel_data);

        jLabel7.setText("Kembalian");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("TRANSAKSI");

        jLabel2.setText("ID_Transaksi");

        btntambah.setText("Tambah");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        jLabel8.setText("Tanggal");

        txtid.setText("...");

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel3.setText("Masukkan Jumlah Barang : ");

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txttotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btntotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(6, 6, 6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtbayar, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(txtkembalian)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btntambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(btnhapus)
                                .addGap(47, 47, 47))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel1)))
                                .addGap(116, 116, 116)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btntransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid)
                    .addComponent(btntransaksi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txttotal))
                        .addGap(18, 18, 18)
                        .addComponent(btntotal))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntambah)
                            .addComponent(btnhapus)
                            .addComponent(jButton1))))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransaksiActionPerformed
        try{
            String sql="select max(right(id_transaksi,3)) as id from penjualan";
            pst = (PreparedStatement) koneksi.prepareStatement(sql);
            Statement stmt = koneksi.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                if(rs.first()==false){
                 txttanggal.setText("T161");
                }else{
                    rs.last();
                    int autoid = rs.getInt(1) + 1;
                        String nomor = String.valueOf(autoid);
                        int noLong = nomor.length();
                        
                        for(int a = 0;a<3-noLong;a++)
                        {nomor = "0" + nomor;}
                        txtid.setText("T"+nomor);
                }       
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btntransaksiActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        int selectedRowIndex = tabel_data.getSelectedRow();
        
        Connection c = buka_koneksi();
        String sqlkode = "Update buku SET `stok`= stok - " + this.txtjumlah.getText() + " "
                + "Where id_buku=" + model.getValueAt(selectedRowIndex, 0) + "";
        int jumlah = Integer.parseInt(txtjumlah.getText());
        int harga = Integer.parseInt((String) model.getValueAt(selectedRowIndex, 3));
        int row3 = jumlah * harga;
        String sqlkode1 = "Insert into penjualan1 (`id_transaksi`,`id_barang`,`nama_barang`,`tanggal`,`jumlah`,`harga`) "
                + "values ('" + this.txtid.getText() + "',"
                + "'" + model.getValueAt(selectedRowIndex, 0) + "',"
                + "'" + model.getValueAt(selectedRowIndex, 1) + "',"
                + "'" + this.txttanggal.getText() + "',"
                + "'" + this.txtjumlah.getText() + "',"
                + "'" + row3 + "')";
        try {
            java.sql.PreparedStatement p1 = (java.sql.PreparedStatement) c.prepareStatement(sqlkode1);
            java.sql.PreparedStatement p2 = (java.sql.PreparedStatement) c.prepareStatement(sqlkode);
            p1.executeUpdate();
            p1.close();
            p2.executeUpdate();
            p2.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan" + ex.getMessage());
        }
        ambil_data_tabel();
        Object[] row = new Object[4];
        row[0] = model.getValueAt(selectedRowIndex, 0);
        row[1] = model.getValueAt(selectedRowIndex, 1);
        row[2] = txtjumlah.getText();
        row[3] = row3;
        model1.addRow(row);
        getSum();
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int selectedRowIndex = jTable2.getSelectedRow();
        
        Connection c = buka_koneksi();
        String sqlkode = "Update buku SET `stok`= stok + " + model1.getValueAt(selectedRowIndex, 2) + " "
                + "Where id_buku=" + model1.getValueAt(selectedRowIndex, 0) + "";
        String sqlkode1 = "Delete From penjualan1 where id_barang = "+ model1.getValueAt(selectedRowIndex, 0);
        try {
            java.sql.PreparedStatement p2 = (java.sql.PreparedStatement) c.prepareStatement(sqlkode);
            java.sql.PreparedStatement p1 = (java.sql.PreparedStatement) c.prepareStatement(sqlkode1);
            p2.executeUpdate();
            p2.close();
            p1.executeUpdate();
            p1.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan" + ex.getMessage());
        }
        ambil_data_tabel();
        ambil_data_tabel1();
        getSum();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        Connection c = buka_koneksi();
        String sqlkode = "Insert into penjualan (`id_transaksi`,`id_barang`,`nama_barang`,`tanggal`,`jumlah`,`harga`) "
                + "select `id_transaksi`,`id_barang`,`nama_barang`,`tanggal`,`jumlah`,`harga` from penjualan1";
        String sqlkode1 = "truncate penjualan1";
        try {
            PreparedStatement p2 = (PreparedStatement) c.prepareStatement(sqlkode);
            PreparedStatement p1 = (PreparedStatement) c.prepareStatement(sqlkode1);
            p2.executeUpdate();
            p2.close();
            p1.executeUpdate();
            p1.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan" + ex.getMessage());
        }
        int total = Integer.parseInt(txttotal.getText());
        int bayar = Integer.parseInt(txtbayar.getText());
        int kembalian = bayar - total;
        String kembali = Integer.toString(kembalian);
        txtkembalian.setText(kembali);
        ambil_data_tabel();
        ambil_data_tabel1();
    }//GEN-LAST:event_btntotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ambil_data_tabel();
        ambil_data_tabel1();
        getSum();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        String query = txtcari.getText().toString();
        filter(query);
    }//GEN-LAST:event_txtcariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btntambah;
    private javax.swing.JButton btntotal;
    private javax.swing.JButton btntransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tabel_data;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtcari;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkembalian;
    private javax.swing.JTextField txttanggal;
    private javax.swing.JLabel txttotal;
    // End of variables declaration//GEN-END:variables
}
